version: '2'

services:
  scanflow-id-aadhar-test:
    image: 'jaiobs/scanflow-id-aadhar:test'
    container_name: 'scanflow-id-aadhar-test'
    # Expose ports [HOST:CONTAINER}
    ports:
      - '3000:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '40k'
    restart: always
